
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: git://github.com/Caascad/pre-commit-hooks
  rev: v3.1.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: git://github.com/Caascad/pre-commit-terraform
  rev: v1.30.0
  hooks:
  - id: terraform_fmt
  - id: terraform_docs_replace
    args: ['--sort-inputs-by-required', '--dest=TERRAFORM.md']
  - id: terraform_tflint
    args: [
    '--args=--enable-rule=terraform_documented_variables
    --enable-rule=terraform_documented_outputs'
    ]
