# Generated by: toolbox make-shell (terraform_1_0.withPlugins (p: [ p.azurerm]))
let
  toolboxSrc = builtins.fromJSON (builtins.readFile ./toolbox.json);
  toolbox = import (builtins.fetchTarball {
    url = "https://github.com/Caascad/toolbox/archive/${toolboxSrc.commit}.tar.gz";
    sha256 = toolboxSrc.sha256;
  }) {};
in with toolbox; pkgs.runCommand "deps" {
  buildInputs = [
    (terraform_1.withPlugins (p: [ p.azurerm]))
    pre-commit
    terraform-docs
    tflint
    vault
    azure-cli
  ];
} ""
